version: '3.4'

services:
  blog-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionString=Server=sql-db;Database=SocialMedia;User Id=admin;Password=admin1234;
      - AllowedOrigins=http://localhost:8080,http://localhost:8081,http://localhost:26110
    ports:
      - "26110:80"
      - "26111:81"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  sql-db:
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
    restart: always
    ports:
      - "26112:5432"


  